'use strict';
// governor/emergency.js — SessionEnd + StopFailure.
// The safety net for the exact scenario that motivated this project: the
// session dies (rate limit, crash, exit) before the model ever got a chance
// to checkpoint. We machine-generate RESUME.auto.md from the journal.
// It NEVER touches an agent-written RESUME.md.

const fs = require('fs');
const path = require('path');
const c = require('./lib/common');

function main() {
  const input = c.readStdinJson();
  const event = input.hook_event_name || '';

  // SessionEnd: always snapshot. StopFailure: only for terminal API errors
  // where work was likely cut off mid-flight.
  const isRateLimitDeath =
    event === 'StopFailure' &&
    /rate_limit|max_output|server_error/i.test(String(input.error_type || ''));
  if (event === 'StopFailure' && !isRateLimitDeath) return;

  const dir = c.projectDir(input.cwd);
  const jfile = path.join(dir, 'journal.jsonl');
  if (!fs.existsSync(jfile)) return;

  const entries = fs
    .readFileSync(jfile, 'utf8')
    .trim()
    .split('\n')
    .map((l) => {
      try {
        return JSON.parse(l);
      } catch {
        return null;
      }
    })
    .filter(Boolean);
  if (!entries.length) return;

  // Scope to the dying session — the journal is shared across sessions and
  // days, and a resume note listing last week's edits is worse than none.
  // Fallback: last 48h, then everything.
  let scoped = entries.filter((e) => e.sid && input.session_id && e.sid === input.session_id);
  if (!scoped.length) scoped = entries.filter((e) => Date.now() - e.t < 48 * 3_600_000);
  if (!scoped.length) scoped = entries;

  const recent = scoped.slice(-40);
  const filesTouched = [
    ...new Set(
      scoped
        .filter((e) => ['Edit', 'Write', 'NotebookEdit'].includes(e.tool) && e.target)
        .map((e) => e.target)
    ),
  ].slice(-25);
  const subagentOutputs = [
    ...new Set(entries.filter((e) => e.tool === 'SubagentStop' && e.target).map((e) => e.target)),
  ];

  const quotaView = c.freshestState(input.session_id || 'unknown');
  const resetNote =
    quotaView.fiveHour && quotaView.fiveHour.resets_at
      ? `5-hour window resets at ${c.fmtClock(quotaView.fiveHour.resets_at)}.`
      : '';

  const lines = [
    '# RESUME.auto.md — machine-generated checkpoint',
    '',
    `> Generated by governor on ${new Date().toISOString()} (event: ${event}` +
      (input.error_type ? `, error: ${input.error_type}` : '') +
      '). The agent did NOT write this; it reconstructs state from the tool journal.',
    resetNote ? `> ${resetNote}` : '',
    '',
    '## Files modified this stretch',
    ...(filesTouched.length ? filesTouched.map((f) => `- ${f}`) : ['- (none recorded)']),
    '',
    '## Preserved subagent outputs (read these before redoing any research)',
    ...(subagentOutputs.length ? subagentOutputs.map((f) => `- ${f}`) : ['- (none)']),
    '',
    '## Last 40 tool calls (newest last)',
    ...recent.map(
      (e) => `- ${new Date(e.t).toISOString().slice(11, 19)} ${e.tool}${e.target ? ': ' + e.target : ''}`
    ),
    '',
    '## On resume',
    '- If RESUME.md exists alongside this file, it is agent-written and authoritative; prefer it.',
    '- Otherwise: check `git status`/`git diff` against the files above, read the subagent outputs, and continue.',
    '',
  ].filter((l) => l !== null);

  fs.writeFileSync(path.join(dir, 'RESUME.auto.md'), lines.join('\n'));
}

try {
  main();
} catch {
  /* never block shutdown */
}
process.exit(0);
